### ISSUE TITLE
商家系统希望能看到每个作品的使用情况(附邀请码: qukgbz)

### ISSUE THREAD

**Issue by CrazyBunQnQ** [zhulu111/ComfyUI_Bxb#10]
#### **邀请码: qukgbz**

希望能够添加一个使用统计的功能，能看到使用者来源、使用者头像缩略图、使用者昵称之类的、以及使用次数

**Comment by zhulu111** [comment]
我们先完善基础功能，统计功能后面逐步实现

**Comment by CrazyBunQnQ** [comment]
> 我们先完善基础功能，统计功能后面逐步实现

大佬加油！！！
