### ISSUE TITLE
H5 界面可以无限获取免费次数(邀请码qukgbz)

### ISSUE THREAD

**Issue by CrazyBunQnQ** [zhulu111/ComfyUI_Bxb#11]
H5 界面，不知道现在是如何区分使用者身份的，存在通过清除 cookie/重复创建隐私浏览器等操作重新获取免费生成次数的情况

> **邀请码: qukgbz**

**Comment by zhulu111** [comment]
是的，浏览器端没有做手机号登录，怕用户觉得麻烦，所以只是做了缓存身份

**Comment by CrazyBunQnQ** [comment]
> 是的，浏览器端没有做手机号登录，怕用户觉得麻烦，所以只是做了缓存身份

那如果我不分享 H5 页面地址用户会拿到这个 URL 么？不会泄露吧~

**Comment by zhulu111** [comment]
目前只能通过分享的方式让用户知道这个链接，所以如果你不分享，别的用户是看不到的
