### ISSUE TITLE
大佬，为啥工作台要一会儿登录一下啊？

### ISSUE THREAD

**Issue by AdamShuo** [zhulu111/ComfyUI_Bxb#14]
大佬，为啥工作台要一会儿登录一下啊？我开着机器挂机哎，客户老是反馈跑不了，进工作台一看要重新扫码登录？能不能不要这么频繁登录，或者改成不登录也能在后台跑工作流封装的应用啊？要不然太不方便了！

**Comment by zhulu111** [comment]
你好，现在就是后台跑的，不需要浏览器端保持登录
