### ISSUE TITLE
开启了之后，没人用的时候GPU怎么也动不动一直20左右的波动？

### ISSUE THREAD

**Issue by cczw2010** [zhulu111/ComfyUI_Bxb#8]
之前没有这种情况，现在装了插件发布成功后，GPU一直是10~30左右的波动使用。

**Comment by cczw2010** [comment]
<img width="378" alt="image" src="https://github.com/user-attachments/assets/2462a45a-cc43-45ec-b330-70ff09404ac7">

**Comment by zhulu111** [comment]
兄弟可以卸载sd变现宝这个插件试下，看看是不是这个插件引起的，在没有生图的情况下，插件只会维护简单的websocket连接的心跳，用不到GPU

**Comment by cczw2010** [comment]
试了 应该是其他插件引起的 🤝
