### ISSUE TITLE
怎么不能写提示词

### ISSUE THREAD

**Issue by bank010** [zhulu111/ComfyUI_Bxb#9]
大家可以试试这个
邀请码：jlv7yp

**Comment by zhulu111** [comment]
兄弟可以看下这个视频教程，如果还有不懂的地方，可以进群联系我。https://www.bilibili.com/video/BV1Bsg8eeEjv

**Comment by CJcrazycool** [comment]
邀请码：e29c6h，填完就可以把工作流变为小程序了
